spells={
['SmolHeal']={desc='',maxcool=1,cooldown=0,mult=-3,minsq=1,maxsq=3},
['Meteor']={desc='',maxcool=2,cooldown=0,mult=3,minsq=1,maxsq=3},
['Lightning']={desc='Hits all enemies. ',maxcool=1,cooldown=0,mult=1.5,minsq=3,maxsq=5},
['Buff']={desc='Adds previously filled squares in row to damage calculations.',maxcool=3,cooldown=0,mult=1,minsq=2,maxsq=2},
['Taunt']={desc='Forces the target to fill in the tiniest possible rows.',maxcool=3,cooldown=0,mult=1,minsq=3,maxsq=3},
['Ice']={desc='Increases target cooldowns by 2.',maxcool=3,cooldown=0,mult=1,minsq=2,maxsq=2},
['Spore']={desc='Decreases target fill-in ranges.',maxcool=3,cooldown=0,mult=1,minsq=2,maxsq=2},
['Poison']={desc='Does squares\' amount of poison damage for 4 turns.',maxcool=3,cooldown=0,mult=1,minsq=1,maxsq=4},
['AntiPsn']={desc='Reduces poison damage by squares\' amount.',maxcool=2,cooldown=0,mult=1,minsq=1,maxsq=4},
['Leech']={desc='Steals HP from target. ',maxcool=1,cooldown=0,mult=2,minsq=2,maxsq=4},
['Mine']={desc='Forces the use of an unseen spell.',maxcool=0,cooldown=0,mult=2,minsq=2,maxsq=2},
['AntiSpore']={desc='Increases your fill-in ranges.',maxcool=3,cooldown=0,mult=1,minsq=2,maxsq=2},
['SoulLeech']={desc='Swaps target hit points with yours.',maxcool=4,cooldown=0,mult=1,minsq=4,maxsq=4},
['Flame']={desc='Decreases your cooldowns by 2.',maxcool=3,cooldown=0,mult=1,minsq=2,maxsq=2},
['Flee']={desc='Escape the encounter early.',maxcool=0,cooldown=0,mult=1,minsq=1,maxsq=1},
['Reflect']={desc='Reflect damage back to enemy.',maxcool=2,cooldown=0,mult=1,minsq=3,maxsq=3},
['MedHeal']={desc='',maxcool=1,cooldown=0,mult=-3,minsq=3,maxsq=7},
['Query']={desc='Ask target about keywords.',maxcool=0,cooldown=0,mult=1,minsq=1,maxsq=1},
['Summon']={desc='',maxcool=2,cooldown=0,mult=1,minsq=4,maxsq=4},
}

cast={
['Meteor']=180,
['Lightning']=50,
['SmolHeal']=120,
['Buff']=120,
['Taunt']=90,
['Ice']=130,
['Spore']=120,
['Poison']=120,
['AntiPsn']=120,
['Leech']=150,
['Mine']=110,
['SoulLeech']=160,
['AntiSpore']=140,
['Flame']=130,
['Flee']=60,
['Reflect']=100,
['MedHeal']=150,
['Query']=90,
['Summon']=140,
}
